from pwn import *

# The base value from the challenge
base = 86844066927987146567678238756515930889952488499230423029593188005934867676767

attempts = 0

while True:
    attempts += 1
    print(f"[*] Attempt {attempts}...")

    # Connect to the CTF server
    # context.log_level = 'error' # Uncomment to hide connection logs once you know it works
    p = remote("chal.thjcc.org", 48764)

    numbers = []
    lucky_run = True

    # Read the first 10 numbers generated by getrandbits(256)
    for _ in range(10):
        line = p.recvline().decode().strip()

        # Parse the number from the line (e.g., "< 12345...")
        if line.startswith("<"):
            num = int(line.split(" ")[1])
            numbers.append(num)

            # If any number is >= base, randrange will reject it and ruin the sequence
            if num >= base:
                lucky_run = False

    # If we hit the ~94% chance of a bad run, drop the connection and try again
    if not lucky_run:
        p.close()
        continue

    print("[+] Lucky run found! All 10 numbers are smaller than base.")
    print("[+] Sending exploit payload...")

    # Send a = -1 and b = 0 to rewind the PRNG state
    p.sendlineafter(b"a>", b"-1")
    p.sendlineafter(b"b>", b"0")

    # Send the exact 10 numbers back to bypass the randrange check
    for num in numbers:
        p.sendlineafter(b"> ", str(num).encode())

    # Catch the flag!
    print("\n[flag] " + p.recvall().decode().strip())
    p.close()
    break
