

# This file was *autogenerated* from the file sol.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0xde26ab651b92a129 = Integer(0xde26ab651b92a129); _sage_const_0x2 = Integer(0x2); _sage_const_0xbd1d620e0990e4af = Integer(0xbd1d620e0990e4af); _sage_const_0x67d8c1bcd4232375 = Integer(0x67d8c1bcd4232375)
modulus = _sage_const_0xde26ab651b92a129 
F = GF(modulus)
g = F(_sage_const_0x2 )
A = F(_sage_const_0xbd1d620e0990e4af )
B = F(_sage_const_0x67d8c1bcd4232375 )

print(discrete_log(A, g))
print(discrete_log(B, g))

