

# This file was *autogenerated* from the file sol.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0xffffff2f = Integer(0xffffff2f); _sage_const_0x2265b1f5 = Integer(0x2265b1f5); _sage_const_0x91b7584a = Integer(0x91b7584a); _sage_const_0xd8f16adf = Integer(0xd8f16adf); _sage_const_0xcd613e30 = Integer(0xcd613e30); _sage_const_0xc386bbc4 = Integer(0xc386bbc4); _sage_const_0x1027c4d1 = Integer(0x1027c4d1); _sage_const_0x414c343c = Integer(0x414c343c); _sage_const_0x1e2feb89 = Integer(0x1e2feb89); _sage_const_0xdc44bf5e = Integer(0xdc44bf5e); _sage_const_0x5aff1cec = Integer(0x5aff1cec); _sage_const_0xe1e9b4c2 = Integer(0xe1e9b4c2); _sage_const_0x01329b92 = Integer(0x01329b92); _sage_const_0x8f9ca92a = Integer(0x8f9ca92a); _sage_const_0x0e45c5b4 = Integer(0x0e45c5b4); _sage_const_0x604a4b91 = Integer(0x604a4b91); _sage_const_0x7081eb59 = Integer(0x7081eb59)
modulus = _sage_const_0xffffff2f 
F = GF(modulus)
test_pt = [F(x) for x in [_sage_const_0x2265b1f5 , _sage_const_0x91b7584a , _sage_const_0xd8f16adf , _sage_const_0xcd613e30 , _sage_const_0xc386bbc4 , _sage_const_0x1027c4d1 , _sage_const_0x414c343c , _sage_const_0x1e2feb89 ]]
test_ct = [F(x) for x in [_sage_const_0xdc44bf5e , _sage_const_0x5aff1cec , _sage_const_0xe1e9b4c2 , _sage_const_0x01329b92 , _sage_const_0x8f9ca92a , _sage_const_0x0e45c5b4 , _sage_const_0x604a4b91 , _sage_const_0x7081eb59 ]]

for i in range(len(test_pt)):
    print(discrete_log(test_ct[i], test_pt[i]))

